events {}

http {
  server {
    listen 80;

    # Forward to Frontend Dashboard (Vite)
    location / {
      proxy_pass http://dashboard:5173;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Forward to Backend API
    location /api {
      proxy_pass http://api:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
